# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Set correct permissions for project files
      run: |
        sudo chown -R $USER:$USER /var/www/web-corporativa
        sudo chmod -R 755 /var/www/web-corporativa
    
    - name: Install node_modules
      run: npm i

    - name: Project build
      run: npm run build --if-present

    - name: Change directory
      run: cd ..

    - name: List PM2 processes
      run: pm2 list

    - name: Stop PM2 process
      run: |
        pm2 stop web-corporativa || echo "Process not found, starting a new one"

    - name: Start PM2 process
      run: pm2 start ecosystem.config.js --only web-corporativa

    - name: Save PM2 state
      run: pm2 save

    - name: Restart nginx 
      run: sudo service nginx restart

